import React, { useState, useEffect } from "react";
import { Loader, Card, FormField } from "../components";

const ReanderCards = ({ data, title }) => {
  if (data && Array.isArray(data)) {
    return data.map((post) => {
      if (post && post._id) {
        return <Card key={post._id} {...post} />;
      }
     
    });
  } else {
    return <p>No data available</p>; // Add your custom message or component here
  }
};

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allpost, setAllpost] = useState([null]);
  const [searchText, setSearchText] = useState("");
  const [searchResults, setSearchResults] = useState(null);
  const [searchTimeout, setSearchTimeout] = useState(null);

  useEffect(() => {
    const fatchPost = async () => {
      setLoading(true);
      try {
        const response = await fetch("https://sahilai.onrender.com/api/post", {
          method: "GET",
          headers: {
            "Content-Type": "application/json",
          },
        });
        if (response.ok) {
          const result = await response.json();
          setAllpost(result.data.reverse());
        }
      } catch (e) {
        console.log(e);
      } finally {
        setLoading(false);
      }
    };
    fatchPost();
  }, []);
  const handlesearchChange = (e) => {
    clearTimeout(searchTimeout);
    setSearchText(e.target.value);

    setSearchTimeout(
      setTimeout(() => {
        const searchResult = allpost.filter(
          (item) =>
            item.name.toLowerCase().include(searchText.toLowerCase()) ||
            item.prompt.toLowerCase().include(searchText.toLowerCase())
        );

        setSearchResults(searchResult);
      }, 500)
    );
  };
  return (
    <>
      <section className="max-w-7xl mx-auto ">
        <div>
          <h1 className="font-extrabold text-[#222328] text-[32px]">
            The Community Showcase
          </h1>
          <p className="mt-2 text-[#666e75] text-[16px] max-w-[500px]">
            Browse through a collection of imaginative and visually stunning
            images generated by Dell-E AI{" "}
          </p>
        </div>
        <div className="mt-16">
          <FormField
            labelName="search Post "
            type="text"
            name="text"
            placeholder="search posts"
            value={searchText}
            handleChange={handlesearchChange}
          />
        </div>
        <div className="mt-10">
          {loading ? (
            <div className="flex justify-center items-center">
              <Loader />
            </div>
          ) : (
            <>
              {searchText && (
                <h2 className="font-medium text-[#666e75] text-xl mb-3">
                  Showing result for{" "}
                  <span className="text-[#222328]">{searchText}</span>
                </h2>
              )}
              <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
                {searchText ? (
                  <ReanderCards
                    data={searchResults}
                    title="No Search Result found"
                  />
                ) : (
                  <ReanderCards data={allpost} title="No post Found" />
                )}
              </div>
            </>
          )}
        </div>
      </section>
    </>
  );
};

export default Home;
